import React from 'react';
import { motion } from 'framer-motion';

export default function TermsOfService() {
  return (
    <motion.div 
      key="terms"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
      className="relative w-full min-h-screen bg-black flex flex-col items-center pt-40 pb-24 overflow-hidden px-6 text-neutral-300"
    >
      <div className="relative z-10 max-w-3xl mx-auto w-full">
        <h1 className="text-4xl md:text-5xl font-bold text-white mb-8" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>Terms of Service</h1>
        <div className="space-y-6 text-sm md:text-base leading-relaxed font-light backdrop-blur-md bg-white/5 p-8 md:p-12 rounded-[2rem] border border-white/10 shadow-2xl">
          <p className="text-emerald-400 font-medium">Last updated: June 2026</p>
          <section>
            <h2 className="text-xl text-white font-medium mb-3 mt-8" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>1. Acceptance of Terms</h2>
            <p>By accessing or using the Neural Leaf ecosystem, including BloomSense and associated platforms, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>
          </section>
          <section>
            <h2 className="text-xl text-white font-medium mb-3 mt-8" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>2. Description of Service</h2>
            <p>Neural Leaf provides an advanced agricultural intelligence platform. We offer AI-driven crop diagnostics, weather integration, and precision treatment recipes. The platform is designed to assist farmers but does not guarantee specific agricultural yields or absolute prevention of crop diseases.</p>
          </section>
          <section>
            <h2 className="text-xl text-white font-medium mb-3 mt-8" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>3. User Responsibilities</h2>
            <p>You are responsible for ensuring that the images and data uploaded for diagnostics are accurate and belong to you. You agree to use the platform for its intended agricultural purposes and not for any malicious activities.</p>
          </section>
          <section>
            <h2 className="text-xl text-white font-medium mb-3 mt-8" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>4. Limitation of Liability</h2>
            <p>The agronomic advice provided by Amania AI and BloomSense is generated by artificial intelligence. While clinical-grade accuracy is targeted, Neural Leaf shall not be held liable for crop loss, reduced yields, or other agricultural damages resulting from the use of our treatment recommendations.</p>
          </section>
        </div>
      </div>
    </motion.div>
  );
}
